export interface Translation {
  title: string;
  subtitle: string;
  copyright: string;
  viewInGallery: string;
  browseGallery: string;
  galleryFeatures: string;
  visualLayout: string;
  search: string;
  languages: string;
  mobile: string;
  toc: string;
  whatIs: string;
  stats: string;
  featuredPrompts: string;
  featuredDesc: string;
  allPrompts: string;
  howToContribute: string;
  license: string;
  acknowledgements: string;
  starHistory: string;
  totalPrompts: string;
  lastUpdated: string;
  metric: string;
  count: string;
  description: string;
  prompt: string;
  generatedVideo: string;
  details: string;
  author: string;
  source: string;
  published: string;
  viewVideo: string;
  clickToView: string;
  morePrompts: string;
  morePromptsDesc: string;
  viewAll: string;
  featured: string;
  // What is section
  whatIsIntro: string;
  textToVideo: string;
  imageToVideo: string;
  videoEditing: string;
  autoAudio: string;
  highResolution: string;
  fastGeneration: string;
  // Gallery features
  galleryFeature1: string;
  galleryFeature2: string;
  galleryFeature3: string;
  galleryFeature4: string;
  // Contribute section
  welcomeContributions: string;
  forkRepo: string;
  addPrompt: string;
  submitPR: string;
  // Footer
  licensedUnder: string;
  autoGenerated: string;
  submitPrompt: string;
  starRepo: string;
  // Featured section extras
  video: string;
  tryItNow: string;
  // Other
  sortedByDate: string;
  handPicked: string;
  githubReadme: string;
  youmindGallery: string;
  linearList: string;
  masonryGrid: string;
  ctrlFOnly: string;
  fullTextSearch: string;
  basic: string;
  fullyResponsive: string;
  aiRecommendation: string;
}

const en: Translation = {
  title: 'Awesome Grok Imagine Prompts',
  subtitle: 'A curated collection of high-quality video generation prompts for xAI\'s Grok Imagine',
  copyright: '**Copyright Notice**: All prompts are collected from the community for educational purposes. If you believe any content infringes on your rights, please [open an issue](https://github.com/YouMind-OpenLab/awesome-grok-imagine-prompts/issues/new) and we will remove it promptly.',
  viewInGallery: 'View in Web Gallery',
  browseGallery: '👉 Browse all Grok Imagine prompts on YouMind',
  galleryFeatures: 'Why use our gallery?',
  visualLayout: 'Video Playback',
  search: 'Search',
  languages: 'AI Recommendation',
  mobile: 'Mobile',
  toc: 'Table of Contents',
  whatIs: 'What is Grok Imagine?',
  stats: 'Statistics',
  featuredPrompts: 'Featured Prompts',
  featuredDesc: 'Hand-picked prompts with outstanding results',
  allPrompts: 'All Prompts',
  howToContribute: 'How to Contribute',
  license: 'License',
  acknowledgements: 'Acknowledgements',
  starHistory: 'Star History',
  totalPrompts: 'Total Prompts',
  lastUpdated: 'Last Updated',
  metric: 'Metric',
  count: 'Count',
  description: 'Description',
  prompt: 'Prompt',
  generatedVideo: 'Generated Video',
  details: 'Details',
  author: 'Author',
  source: 'Source',
  published: 'Published',
  viewVideo: '🎬 View Video →',
  clickToView: 'Click to view full video',
  morePrompts: 'More Prompts Available',
  morePromptsDesc: 'more prompts not shown here',
  viewAll: '👉 View all prompts in our Web Gallery',
  featured: 'Featured',
  whatIsIntro: '**Grok Imagine** is a video generation model by **xAI**, integrated into the Grok AI assistant on X (Twitter). It generates high-quality, cinematic videos from text prompts and images with stunning visual quality.',
  textToVideo: '🎬 **Text-to-Video** — Generate videos from text descriptions',
  imageToVideo: '🖼️ **Image-to-Video** — Animate static images into dynamic videos',
  videoEditing: '✂️ **Video Editing** — Edit and transform existing videos',
  autoAudio: '🔊 **Auto Audio** — Automatic dubbing and background music',
  highResolution: '📐 **720p+ Resolution** — 10-15 seconds duration per clip',
  fastGeneration: '⚡ **Fast Generation** — Under 20 seconds generation time',
  galleryFeature1: '✨ Beautiful masonry grid layout',
  galleryFeature2: '🔍 Full-text search and filters',
  galleryFeature3: '🌍 16 languages support',
  galleryFeature4: '📱 Mobile-optimized experience',
  welcomeContributions: 'Contributions are welcome! Please feel free to submit a Pull Request.',
  forkRepo: 'Fork the repository',
  addPrompt: 'Add your prompt following the existing format',
  submitPR: 'Submit a PR',
  licensedUnder: 'This work is licensed under [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/). You are free to share and adapt, with appropriate credit.',
  autoGenerated: 'This README is automatically generated. Last updated:',
  submitPrompt: 'Submit a Prompt',
  starRepo: 'Star this repo',
  sortedByDate: 'Sorted by publish date (newest first)',
  handPicked: 'Hand-picked by our team for exceptional quality and creativity',
  video: 'Video',
  tryItNow: 'Try it now →',
  githubReadme: 'GitHub README',
  youmindGallery: 'youmind.com Gallery',
  linearList: '❌ Static thumbnails only',
  masonryGrid: '✅ Full video playback with streaming',
  ctrlFOnly: 'Ctrl+F only',
  fullTextSearch: 'Multi-field fuzzy matching search',
  basic: 'Basic',
  fullyResponsive: 'Fully responsive',
  aiRecommendation: 'AI-powered prompt recommendations',
};

const zh: Translation = {
  title: 'Grok Imagine 视频提示词大全',
  subtitle: 'xAI Grok Imagine 高质量视频生成提示词精选集合',
  copyright: '**版权声明**：所有提示词均收集自社区，仅供教育目的使用。如果您认为任何内容侵犯了您的权利，请[提交 issue](https://github.com/YouMind-OpenLab/awesome-grok-imagine-prompts/issues/new)，我们将立即移除。',
  viewInGallery: '在网页画廊中查看',
  browseGallery: '👉 在 YouMind 浏览所有 Grok Imagine 提示词',
  galleryFeatures: '为什么使用画廊？',
  visualLayout: '视频播放',
  search: '搜索',
  languages: 'AI 推荐',
  mobile: '移动端',
  toc: '目录',
  whatIs: '什么是 Grok Imagine？',
  stats: '统计数据',
  featuredPrompts: '精选提示词',
  featuredDesc: '精心挑选的高质量提示词',
  allPrompts: '所有提示词',
  howToContribute: '如何贡献',
  license: '许可证',
  acknowledgements: '致谢',
  starHistory: 'Star 历史',
  totalPrompts: '提示词总数',
  lastUpdated: '最后更新',
  metric: '指标',
  count: '数量',
  description: '描述',
  prompt: '提示词',
  generatedVideo: '生成视频',
  details: '详情',
  author: '作者',
  source: '来源',
  published: '发布时间',
  viewVideo: '🎬 查看视频 →',
  clickToView: '点击查看完整视频',
  morePrompts: '更多提示词',
  morePromptsDesc: '更多提示词未在此显示',
  viewAll: '👉 在网页画廊中查看所有提示词',
  featured: '精选',
  whatIsIntro: '**Grok Imagine** 是 **xAI** 推出的视频生成模型，集成在 X（Twitter）平台的 Grok AI 助手中。它可以通过文本提示词和图片生成高质量、电影级的视频。',
  textToVideo: '🎬 **文本生成视频** — 根据文字描述生成视频',
  imageToVideo: '🖼️ **图片生成视频** — 将静态图片转化为动态视频',
  videoEditing: '✂️ **视频编辑** — 编辑和转换现有视频',
  autoAudio: '🔊 **自动音频** — 自动配音和背景音乐',
  highResolution: '📐 **720p+ 分辨率** — 每个片段 10-15 秒时长',
  fastGeneration: '⚡ **快速生成** — 20 秒内完成生成',
  galleryFeature1: '✨ 精美的瀑布流网格布局',
  galleryFeature2: '🔍 全文搜索和筛选',
  galleryFeature3: '🌍 支持 16 种语言',
  galleryFeature4: '📱 移动端优化体验',
  welcomeContributions: '欢迎贡献！请随时提交 Pull Request。',
  forkRepo: 'Fork 仓库',
  addPrompt: '按照现有格式添加您的提示词',
  submitPR: '提交 PR',
  licensedUnder: '本作品根据 [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/) 许可。您可以自由分享和改编，但需给予适当署名。',
  autoGenerated: '此 README 自动生成。最后更新：',
  submitPrompt: '提交提示词',
  starRepo: '给仓库点星',
  sortedByDate: '按发布日期排序（最新优先）',
  handPicked: '由我们的团队精心挑选，具有卓越的质量和创造力',
  video: '视频',
  tryItNow: '立即体验 →',
  githubReadme: 'GitHub README',
  youmindGallery: 'youmind.com 画廊',
  linearList: '❌ 仅静态缩略图',
  masonryGrid: '✅ 完整视频播放支持流媒体',
  ctrlFOnly: '仅 Ctrl+F',
  fullTextSearch: '多字段模糊匹配搜索',
  basic: '基础',
  fullyResponsive: '完全响应式',
  aiRecommendation: 'AI 智能提示词推荐',
};

const zhTW: Translation = {
  ...zh,
  title: 'Grok Imagine 視頻提示詞大全',
  subtitle: 'xAI Grok Imagine 高質量視頻生成提示詞精選集合',
  copyright: '**版權聲明**：所有提示詞均收集自社區，僅供教育目的使用。如果您認為任何內容侵犯了您的權利，請[提交 issue](https://github.com/YouMind-OpenLab/awesome-grok-imagine-prompts/issues/new)，我們將立即移除。',
  viewInGallery: '在網頁畫廊中查看',
  browseGallery: '👉 在 YouMind 瀏覽所有 Grok Imagine 提示詞',
  galleryFeatures: '為什麼使用畫廊？',
  visualLayout: '視頻播放',
  languages: 'AI 推薦',
  mobile: '移動端',
  toc: '目錄',
  whatIs: '什麼是 Grok Imagine？',
  stats: '統計數據',
  featuredPrompts: '精選提示詞',
  featuredDesc: '精心挑選的高品質提示詞',
  allPrompts: '所有提示詞',
  howToContribute: '如何貢獻',
  license: '許可證',
  acknowledgements: '致謝',
  starHistory: 'Star 歷史',
  totalPrompts: '提示詞總數',
  lastUpdated: '最後更新',
  metric: '指標',
  count: '數量',
  description: '描述',
  prompt: '提示詞',
  generatedVideo: '生成視頻',
  details: '詳情',
  author: '作者',
  source: '來源',
  published: '發布時間',
  viewVideo: '🎬 查看視頻 →',
  clickToView: '點擊查看完整視頻',
  morePrompts: '更多提示詞',
  morePromptsDesc: '更多提示詞未在此顯示',
  viewAll: '👉 在網頁畫廊中查看所有提示詞',
  featured: '精選',
  whatIsIntro: '**Grok Imagine** 是 **xAI** 推出的視頻生成模型，集成在 X（Twitter）平台的 Grok AI 助手中。它可以通過文本提示詞和圖片生成高質量、電影級的視頻。',
  textToVideo: '🎬 **文本生成視頻** — 根據文字描述生成視頻',
  imageToVideo: '🖼️ **圖片生成視頻** — 將靜態圖片轉化為動態視頻',
  videoEditing: '✂️ **視頻編輯** — 編輯和轉換現有視頻',
  autoAudio: '🔊 **自動音頻** — 自動配音和背景音樂',
  highResolution: '📐 **720p+ 分辨率** — 每個片段 10-15 秒時長',
  fastGeneration: '⚡ **快速生成** — 20 秒內完成生成',
  galleryFeature1: '✨ 精美的瀑布流網格佈局',
  galleryFeature2: '🔍 全文搜索和篩選',
  galleryFeature3: '🌍 支持 16 種語言',
  galleryFeature4: '📱 移動端優化體驗',
  welcomeContributions: '歡迎貢獻！請隨時提交 Pull Request。',
  forkRepo: 'Fork 倉庫',
  addPrompt: '按照現有格式添加您的提示詞',
  submitPR: '提交 PR',
  licensedUnder: '本作品根據 [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/) 許可。您可以自由分享和改編，但需給予適當署名。',
  autoGenerated: '此 README 自動生成。最後更新：',
  submitPrompt: '提交提示詞',
  starRepo: '給倉庫點星',
  sortedByDate: '按發布日期排序（最新優先）',
  handPicked: '由我們的團隊精心挑選，具有卓越的質量和創造力',
  video: '視頻',
  tryItNow: '立即體驗 →',
  githubReadme: 'GitHub README',
  youmindGallery: 'youmind.com 畫廊',
  linearList: '❌ 僅靜態縮略圖',
  masonryGrid: '✅ 完整視頻播放支持流媒體',
  ctrlFOnly: '僅 Ctrl+F',
  fullTextSearch: '多字段模糊匹配搜索',
  basic: '基礎',
  fullyResponsive: '完全響應式',
  aiRecommendation: 'AI 智能提示詞推薦',
};

const ja: Translation = {
  ...en,
  title: 'Grok Imagine 動画プロンプト集',
  subtitle: 'xAI の Grok Imagine 向け高品質動画生成プロンプトコレクション',
  copyright: '**著作権に関する通知**: すべてのプロンプトは教育目的でコミュニティから収集されています。権利を侵害していると思われるコンテンツがある場合は、[issue を作成](https://github.com/YouMind-OpenLab/awesome-grok-imagine-prompts/issues/new)してください。速やかに削除いたします。',
  viewInGallery: 'Web ギャラリーで見る',
  browseGallery: '👉 YouMind で Grok Imagine プロンプトをすべて見る',
  galleryFeatures: 'ギャラリーを使用する理由',
  visualLayout: '動画再生',
  languages: 'AI レコメンド',
  mobile: 'モバイル',
  toc: '目次',
  whatIs: 'Grok Imagine とは？',
  stats: '統計',
  featuredPrompts: 'おすすめプロンプト',
  featuredDesc: '厳選された高品質プロンプト',
  allPrompts: 'すべてのプロンプト',
  howToContribute: '貢献方法',
  license: 'ライセンス',
  acknowledgements: '謝辞',
  starHistory: 'スター履歴',
  totalPrompts: 'プロンプト総数',
  lastUpdated: '最終更新',
  metric: '指標',
  count: '数',
  description: '説明',
  prompt: 'プロンプト',
  generatedVideo: '生成動画',
  details: '詳細',
  author: '作者',
  source: 'ソース',
  published: '公開日',
  viewVideo: '🎬 動画を見る →',
  clickToView: '動画をクリックして再生',
  morePrompts: 'その他のプロンプト',
  morePromptsDesc: 'さらに多くのプロンプトがあります',
  viewAll: '👉 Web ギャラリーですべてのプロンプトを見る',
  featured: 'おすすめ',
  whatIsIntro: '**Grok Imagine** は **xAI** が開発した動画生成モデルで、X（Twitter）プラットフォーム上の Grok AI アシスタントに統合されています。テキストプロンプトや画像から高品質でシネマティックな動画を生成します。',
  textToVideo: '🎬 **テキストから動画** — テキスト説明から動画を生成',
  imageToVideo: '🖼️ **画像から動画** — 静止画をダイナミックな動画に変換',
  videoEditing: '✂️ **動画編集** — 既存の動画を編集・変換',
  autoAudio: '🔊 **自動音声** — 自動吹き替えとBGM',
  highResolution: '📐 **720p+解像度** — クリップあたり10-15秒',
  fastGeneration: '⚡ **高速生成** — 20秒以内で生成完了',
  galleryFeature1: '✨ 美しいメイソンリグリッドレイアウト',
  galleryFeature2: '🔍 全文検索とフィルター',
  galleryFeature3: '🌍 16言語サポート',
  galleryFeature4: '📱 モバイル最適化体験',
  welcomeContributions: '貢献を歓迎します！お気軽にPull Requestを提出してください。',
  forkRepo: 'リポジトリをフォーク',
  addPrompt: '既存のフォーマットに従ってプロンプトを追加',
  submitPR: 'PRを提出',
  licensedUnder: '本作品は [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/) の下でライセンスされています。適切なクレジットを付与すれば、自由に共有・改変できます。',
  autoGenerated: 'このREADMEは自動生成されています。最終更新：',
  submitPrompt: 'プロンプトを提出',
  starRepo: 'このリポジトリにスターを付ける',
  sortedByDate: '公開日でソート（新しい順）',
  handPicked: '優れた品質と創造性のためにチームが厳選',
  video: '動画',
  tryItNow: '今すぐ試す →',
  githubReadme: 'GitHub README',
  youmindGallery: 'youmind.com ギャラリー',
  linearList: '❌ 静止サムネイルのみ',
  masonryGrid: '✅ フル動画再生（ストリーミング対応）',
  ctrlFOnly: 'Ctrl+Fのみ',
  fullTextSearch: '複数フィールドのあいまい検索',
  basic: '基本',
  fullyResponsive: '完全レスポンシブ',
  aiRecommendation: 'AI 搭載プロンプト推薦',
};

const ko: Translation = {
  ...en,
  title: 'Grok Imagine 비디오 프롬프트 모음',
  subtitle: 'xAI Grok Imagine을 위한 고품질 비디오 생성 프롬프트 컬렉션',
  copyright: '**저작권 고지**: 모든 프롬프트는 교육 목적으로 커뮤니티에서 수집되었습니다. 귀하의 권리를 침해하는 콘텐츠가 있다고 생각되면 [이슈를 열어주세요](https://github.com/YouMind-OpenLab/awesome-grok-imagine-prompts/issues/new). 즉시 삭제하겠습니다.',
  viewInGallery: '웹 갤러리에서 보기',
  browseGallery: '👉 YouMind에서 모든 Grok Imagine 프롬프트 둘러보기',
  galleryFeatures: '갤러리를 사용하는 이유는?',
  visualLayout: '비디오 재생',
  languages: 'AI 추천',
  mobile: '모바일',
  toc: '목차',
  whatIs: 'Grok Imagine이란?',
  stats: '통계',
  featuredPrompts: '추천 프롬프트',
  featuredDesc: '엄선된 고품질 프롬프트',
  allPrompts: '모든 프롬프트',
  howToContribute: '기여하는 방법',
  license: '라이선스',
  acknowledgements: '감사의 말',
  starHistory: '스타 히스토리',
  totalPrompts: '총 프롬프트 수',
  lastUpdated: '마지막 업데이트',
  metric: '지표',
  count: '수',
  description: '설명',
  prompt: '프롬프트',
  generatedVideo: '생성된 비디오',
  details: '상세 정보',
  author: '작성자',
  source: '출처',
  published: '게시일',
  viewVideo: '🎬 비디오 보기 →',
  clickToView: '클릭하여 전체 비디오 보기',
  morePrompts: '더 많은 프롬프트',
  morePromptsDesc: '여기에 표시되지 않은 더 많은 프롬프트가 있습니다',
  viewAll: '👉 웹 갤러리에서 모든 프롬프트 보기',
  featured: '추천',
  whatIsIntro: '**Grok Imagine**은 **xAI**가 개발한 비디오 생성 모델로, X(Twitter) 플랫폼의 Grok AI 어시스턴트에 통합되어 있습니다. 텍스트 프롬프트와 이미지로 고품질 시네마틱 비디오를 생성합니다.',
  textToVideo: '🎬 **텍스트에서 비디오** — 텍스트 설명으로 비디오 생성',
  imageToVideo: '🖼️ **이미지에서 비디오** — 정적 이미지를 동적 비디오로 변환',
  videoEditing: '✂️ **비디오 편집** — 기존 비디오 편집 및 변환',
  autoAudio: '🔊 **자동 오디오** — 자동 더빙 및 배경 음악',
  highResolution: '📐 **720p+ 해상도** — 클립당 10-15초 길이',
  fastGeneration: '⚡ **빠른 생성** — 20초 이내 생성 완료',
  galleryFeature1: '✨ 아름다운 메이슨리 그리드 레이아웃',
  galleryFeature2: '🔍 전체 텍스트 검색 및 필터',
  galleryFeature3: '🌍 16개 언어 지원',
  galleryFeature4: '📱 모바일 최적화 경험',
  welcomeContributions: '기여를 환영합니다! Pull Request를 자유롭게 제출해 주세요.',
  forkRepo: '저장소 포크',
  addPrompt: '기존 형식에 따라 프롬프트 추가',
  submitPR: 'PR 제출',
  licensedUnder: '이 작품은 [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)에 따라 라이선스됩니다. 적절한 크레딧을 부여하면 자유롭게 공유하고 수정할 수 있습니다.',
  autoGenerated: '이 README는 자동으로 생성됩니다. 마지막 업데이트:',
  submitPrompt: '프롬프트 제출',
  starRepo: '이 저장소에 스타 추가',
  sortedByDate: '게시일 기준 정렬(최신순)',
  handPicked: '팀이 뛰어난 품질과 창의성을 위해 엄선',
  video: '비디오',
  tryItNow: '지금 체험하기 →',
  githubReadme: 'GitHub README',
  youmindGallery: 'youmind.com 갤러리',
  linearList: '❌ 정적 썸네일만',
  masonryGrid: '✅ 풀 비디오 재생 (스트리밍 지원)',
  ctrlFOnly: 'Ctrl+F만',
  fullTextSearch: '다중 필드 퍼지 매칭 검색',
  basic: '기본',
  fullyResponsive: '완전 반응형',
  aiRecommendation: 'AI 기반 프롬프트 추천',
};

const th: Translation = { ...en, title: 'สุดยอด Grok Imagine Prompts', subtitle: 'คอลเลกชันพรอมต์สร้างวิดีโอคุณภาพสูงสำหรับ Grok Imagine ของ xAI' };
const vi: Translation = { ...en, title: 'Tuyển tập Grok Imagine Prompts', subtitle: 'Bộ sưu tập prompt tạo video chất lượng cao cho Grok Imagine của xAI' };
const hi: Translation = { ...en, title: 'शानदार Grok Imagine प्रॉम्पट्स', subtitle: 'xAI के Grok Imagine के लिए उच्च गुणवत्ता वाले वीडियो जनरेशन प्रॉम्पट्स का संग्रह' };
const es: Translation = { ...en, title: 'Prompts de Video Grok Imagine Increíbles', subtitle: 'Una colección curada de prompts de generación de video de alta calidad para Grok Imagine de xAI' };
const de: Translation = { ...en, title: 'Tolle Grok Imagine Video-Prompts', subtitle: 'Eine kuratierte Sammlung hochwertiger Videogenerierungs-Prompts für xAI Grok Imagine' };
const fr: Translation = { ...en, title: 'Prompts Vidéo Grok Imagine Géniaux', subtitle: 'Une collection de prompts de génération vidéo de haute qualité pour Grok Imagine de xAI' };
const it: Translation = { ...en, title: 'Fantastici Prompt Video Grok Imagine', subtitle: 'Una raccolta curata di prompt di generazione video di alta qualità per Grok Imagine di xAI' };
const pt: Translation = { ...en, title: 'Prompts de Vídeo Grok Imagine Incríveis', subtitle: 'Uma coleção curada de prompts de geração de vídeo de alta qualidade para o Grok Imagine da xAI' };
const tr: Translation = { ...en, title: 'Harika Grok Imagine Video İstemleri', subtitle: 'xAI Grok Imagine için yüksek kaliteli video oluşturma istemleri koleksiyonu' };

const I18N: Record<string, Translation> = {
  'en': en,
  'zh': zh,
  'zh-TW': zhTW,
  'ja-JP': ja,
  'ko-KR': ko,
  'th-TH': th,
  'vi-VN': vi,
  'hi-IN': hi,
  'es-ES': es,
  'es-419': es,
  'de-DE': de,
  'fr-FR': fr,
  'it-IT': it,
  'pt-BR': pt,
  'pt-PT': pt,
  'tr-TR': tr,
};

export function t(key: keyof Translation, locale: string): string {
  if (I18N[locale] && I18N[locale][key]) {
    return I18N[locale][key];
  }
  return en[key] || key;
}
